name: GitHub Actions Worflow iac
run-name: ${{ github.actor }} is deploying iac 
# on: [push]
on: workflow_dispatch
# on:
#   workflow_dispatch:
#     inputs:
#       destroy:
#         type: boolean
#         description: Destroy environment?
#         required: true
#         default: false

#   pull_request:
#     paths:
#     - infra/**

env:
  tf_actions_working_dir: iac/terraform

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: Terraform plan & apply
    #runs-on: self-hosted
    # runs-on: ubuntu-latest
    #runs-on: [self-hosted, ManagedDevOps.Pool=datasynchro-manages-pool-github]
    # runs-on: [self-hosted, ManagedDevOps.Pool=datasynchro-manages-pool-github, ManagedDevOps.ImageOverride=/subscriptions/023b2039-5c23-44b8-844e-c002f8ed431d/resourceGroups/RG_MANAGED_DEVOPS_POOL/providers/Microsoft.Compute/galleries/datasynchro_compute_gallery/images/datasynchro_vm_image_definition-github/versions/latest]
    runs-on: [self-hosted, ManagedDevOps.Pool=datasynchro-manages-pool-github, ManagedDevOps.ImageOverride=/subscriptions/023b2039-5c23-44b8-844e-c002f8ed431d/Providers/Microsoft.Compute/Locations/westeurope/Publishers/microsoftvisualstudio/ArtifactTypes/VMImage/Offers/visualstudio2022/Skus/vs-2022-ent-latest-ws2022/versions/latest]
    environment: sandbox
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Install Azure CLI
      run: |
        Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet /qn /norestart'

    - name: Use Azure CLI
      run: az --version

    - name: Log in to Azure using OIDC
      uses: azure/login@v1
      with:
        client-id: 68b5381d-15a5-4084-8364-f614904bb5f2
        tenant-id: f12a747a-cddf-4426-96ff-ebe055e215a3
        subscription-id: 023b2039-5c23-44b8-844e-c002f8ed431d

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Terraform Init
      id: init
      run: terraform init -var-file="github.tfvars"
      env:
        ARM_CLIENT_ID: 68b5381d-15a5-4084-8364-f614904bb5f2
        ARM_SUBSCRIPTION_ID: 023b2039-5c23-44b8-844e-c002f8ed431d
        ARM_TENANT_ID: f12a747a-cddf-4426-96ff-ebe055e215a3
        ARM_USE_OIDC: true
 
    - name: Terraform Plan
      id: plan
      run: terraform plan  --out=out.tfplan -var-file="github.tfvars"
      env:
        ARM_CLIENT_ID: 68b5381d-15a5-4084-8364-f614904bb5f2
        ARM_SUBSCRIPTION_ID: 023b2039-5c23-44b8-844e-c002f8ed431d
        ARM_TENANT_ID: f12a747a-cddf-4426-96ff-ebe055e215a3
        ARM_USE_OIDC: true
     
    - name: Upload the plan
      uses: actions/upload-artifact@v3
      with:
        name: tf-plan
        path: ${{ env.tf_actions_working_dir }}/out.tfplan

    - name: Download the plan
      uses: actions/download-artifact@v3
      with:
        name: tf-plan
        path: ${{ env.tf_actions_working_dir }}

    - name: Apply the plan
      id: apply
      run: terraform apply -no-color -auto-approve out.tfplan 
      env:
        ARM_CLIENT_ID: 68b5381d-15a5-4084-8364-f614904bb5f2
        ARM_SUBSCRIPTION_ID: 023b2039-5c23-44b8-844e-c002f8ed431d
        ARM_TENANT_ID: f12a747a-cddf-4426-96ff-ebe055e215a3
        ARM_USE_OIDC: true